# Site settings
site: Ephesus
title: Ephesus - Minimalist Jekyll Theme
keywords: ephesus, blog
description: >-
  Ephesus - Minimalist Jekyll Theme
lang: en-US
timezone:  Europe/Istanbul
repo: https://github.com/jpadhye/Ephesus # site repo [optional]
google_verify:      XXX # Put your Google Verification here
google_analytics:   UA-XXXXXXXX-00 # Put your Google Analytics code
discus-identifier:  XXX

# Author settings
author:
  name: Jaideep Padhye
  bio: Engineering Leader @AppDynamics <br> Open Source Enthusiast
  picture: assets/images/profile.jpg 
  github: jpadhye # github username
  #twitter: jpadhye # twitter username
  #facebook: jpadhye # facebook username
  instagram: jpadhye # instagram username
  #youtube: https://www.youtube.com/channel/UCMmAto-wxBootXN91AzBiDg # youtube username
  linkedin: jpadhye # linkedin username
  #email: your-email@email.com # email adress


# URL settings
url: "jpadhye.github.io" # Domain Name of host. [username].github.io for github pages
permalink: pretty

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge


exclude:
  - .jekyll-cache
  - .obsidian
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - CONTRIBUTING.md

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-relative-links
paginate: 20
paginate_path: "/page/:num"

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:slug
  
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

relative_links:
  enabled:     true
  collections: false